### ISSUE TITLE
Handwritten TypeScript instances for higher-order ADTs

### ISSUE THREAD

**Issue by maxhallinan** [codedownio/aeson-typescript#18]
I have a type representing form fields. The field values can be one of several types. Those values can be optional or required, depending on the endpoint. For example, the values are optional in the request to create the form and required in the request to submit the form.

Here is a simplified version of that type:

```
data FieldType f 
  = TextField (f Text)
  | IntField (f Int)

type OptionalField = FieldType Maybe

type RequiredField = FieldType Identity
```

My intention was to generate TypeScript types like this:

```
type TOptionalField = IOptionalTextField | IOptionalIntField

interface IOptionalTextField {
  tag: 'OptionalTextField'
  value?: string
}

interface IOptionalIntField {
  tag: 'OptionalIntField'
  value?: number
}

type TRequiredField = IRequiredTextField | IRequiredIntField

interface IRequiredTextField {
  tag: 'RequiredTextField'
  value: string
}

interface IRequiredIntField {
  tag: 'RequiredIntField'
  value: number
}
```

But I can't do this because the `TSDeclaration` constructors aren't exported. And a `TypeScript` instance for this can't be derived because TypeScript doesn't have higher-order generics. Any thoughts on this? Writing the instance by hand is more error prone and probably not desirable in most cases. But without that ability, I am blocked from using a sensible Haskell type.

**Comment by thomasjm** [comment]
For two separate endpoints I would normally just create two separate data types, which can use `Maybe` or not as they see fit. I'm guessing the reason you want to parameterize over `Maybe` or `Identity` is because these would be large/burdensome to duplicate?

I guess you could imagine this library supporting a call like `$(deriveTypeScript ''FieldType)`, which doesn't compile today. But as you say, I'm not sure what instance it would generate given the higher kinded argument. In general I find when you want to interface your types with JSON there is less friction when you write more [boring](https://www.snoyman.com/blog/2019/11/boring-haskell-manifesto) Haskell :P.

There have been previous discussions about exporting the `TSDeclaration` constructors but I'm not sure how it  would help you? They're just a thin wrapper around TypeScript interface and type declarations, so they wouldn't prevent many errors over just writing your instances as strings.

For what it's worth, the TypeScript you describe is what you'd get if you wrote something like

```haskell
data OptionalField = OptionalFieldText { optionalFieldText :: Maybe Text } 
                   | OptionalFieldInt { optionalFieldInt :: Maybe Int }
data RequiredField = RequiredFieldText { requiredFieldText :: Text } 
                   | RequiredFieldInt { requiredFieldInt :: Int }
```

(With appropriate [Aeson options](http://hackage.haskell.org/package/aeson-1.4.7.1/docs/Data-Aeson-TH.html#t:Options).)

**Comment by maxhallinan** [comment]
Thanks for the quick reply! You're right - constructing TSDeclaration by hand leads is more error prone. For example, I can implement `getTypeScriptDeclarations` in a way that won't compile if I'm missing a field type. It's easier for a handwritten TS type to get out of sync with the Haskell type. Anyways, I just wanted to add an additional anecdata point to the discussion about exporting constructors. Thanks for considering it.
