### ISSUE TITLE
Add TypeScript instance for UTCTime

### ISSUE THREAD

**Issue by bitc** [codedownio/aeson-typescript#3]
I believe it should be "string"

**Comment by thomasjm** [comment]
I deliberately left the `UTCTime` instance out of the library so I would have an example to point to in the docs to show how to add custom instances :). See here:

https://hackage.haskell.org/package/aeson-typescript-0.1.0.6/docs/Data-Aeson-TypeScript-TH.html

**Comment by bitc** [comment]
Oh, I see. But won't that be an orphan instance?

**Comment by thomasjm** [comment]
That's true, but it shouldn't cause any problems since only once instance should exist for a given type (it has to match up with the Aeson instance after all).

In general, I need to strike a balance between bundling instances for more packages and keeping the dependencies from being too heavy--you wouldn't want to compile a bunch of libraries you don't even use just because `aeson-typescript` pulls them in. The `time` library seemed like a reasonable place to draw the line.

I'm going to hit close on this issue but feel free to reach out if you have other issues!
